// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async heartbeat(): Promise<Heartbeat> {
    return await TAURI_INVOKE("heartbeat");
  },
  /**
   * Load the fixed backend-owned settings document and perform the one-time
   * import of bounded legacy renderer values when needed.
   */
  async initializeSettings(
    legacy: LegacySettingsImport,
  ): Promise<SettingsLoadResult> {
    return await TAURI_INVOKE("initialize_settings", { legacy });
  },
  async setSettingsLanguage(
    language: SettingsLanguage,
  ): Promise<SettingsSnapshot> {
    return await TAURI_INVOKE("set_settings_language", { language });
  },
  async getSettingsMirrorPreset(
    deviceIdentity: string,
  ): Promise<MirrorPreset | null> {
    return await TAURI_INVOKE("get_settings_mirror_preset", { deviceIdentity });
  },
  async setSettingsMirrorPreset(
    deviceIdentity: string,
    preset: MirrorPreset,
  ): Promise<SettingsSnapshot> {
    return await TAURI_INVOKE("set_settings_mirror_preset", {
      deviceIdentity,
      preset,
    });
  },
  async resetSettingsMirrorPreset(
    deviceIdentity: string,
  ): Promise<SettingsSnapshot> {
    return await TAURI_INVOKE("reset_settings_mirror_preset", {
      deviceIdentity,
    });
  },
  async resetSettings(scope: SettingsScope): Promise<SettingsSnapshot> {
    return await TAURI_INVOKE("reset_settings", { scope });
  },
  /**
   * Export only a named settings scope through a backend-issued save grant.
   * The internal settings path never crosses IPC.
   */
  async exportSettings(
    scope: SettingsScope,
    pathGrant: string,
  ): Promise<SettingsExportResult> {
    return await TAURI_INVOKE("export_settings", {
      scope,
      path_grant: pathGrant,
    });
  },
  /**
   * List the saved Logcat query presets for the global scope and, when a device
   * identity is supplied, that device's scope. Only query definitions are
   * stored; captured log lines never enter the settings document.
   */
  async listLogcatQueries(
    deviceIdentity: string | null,
  ): Promise<LogcatQueryLibrary> {
    return await TAURI_INVOKE("list_logcat_queries", { deviceIdentity });
  },
  /**
   * Persist the full ordered list of Logcat query presets for one scope. This
   * single write covers create, rename, duplicate, reorder, and delete; an empty
   * list clears the scope. Each preset is validated (including a linear-time
   * regex guard) before it is written.
   */
  async saveLogcatQueries(
    scope: LogcatQueryScope,
    deviceIdentity: string | null,
    queries: LogcatQuery[],
  ): Promise<LogcatQueryLibrary> {
    return await TAURI_INVOKE("save_logcat_queries", {
      scope,
      deviceIdentity,
      queries,
    });
  },
  /**
   * Capture the current UI hierarchy with `uiautomator dump`. This is a
   * read-only inspection: it prints the hierarchy to `/dev/tty` (no device-side
   * file is written) and the renderer never controls any path.
   */
  async captureLayout(target: DeviceTarget): Promise<LayoutSnapshot> {
    return await TAURI_INVOKE("capture_layout", { target });
  },
  /**
   * Persist a captured UI hierarchy XML through a one-shot path grant. The size
   * bound keeps the IPC and host write bounded, mirroring the Logcat export.
   */
  async saveLayoutExport(pathGrant: string, contents: string): Promise<string> {
    return await TAURI_INVOKE("save_layout_export", {
      path_grant: pathGrant,
      contents,
    });
  },
  /**
   * Run a bounded, non-elevated, read-only host connection scan. The report
   * contains state counts and redacted configuration presence only; it never
   * persists device identifiers, USB instance IDs, environment values, or keys.
   */
  async runHostDoctor(): Promise<HostDoctorReport> {
    return await TAURI_INVOKE("run_host_doctor");
  },
  async listDevices(): Promise<ListDevicesResult> {
    return await TAURI_INVOKE("list_devices");
  },
  /**
   * Maintain one app-wide live device snapshot. The frontend starts this once
   * and all routes subscribe to the renderer's shared external store instead
   * of polling ADB independently.
   */
  async watchDevices(
    operationId: string,
    onEvent: TAURI_CHANNEL<DeviceLifecycleEvent>,
  ): Promise<null> {
    return await TAURI_INVOKE("watch_devices", {
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Restart the local ADB server and reconnect only offline transports. This is
   * a host-wide mutation, so the renderer must review the exact argv and send
   * an explicit confirmation. A synced pending record lands before `kill-server`.
   */
  async recoverAdb(
    confirmed: boolean,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<AdbRecoveryResult> {
    return await TAURI_INVOKE("recover_adb", {
      confirmed,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Open a backend-owned native file dialog and retain its result as a short-
   * lived, purpose-scoped, one-shot grant. Privileged commands accept only the
   * opaque grant id, never a renderer-authored host path.
   */
  async selectHostPath(
    purpose: HostPathPurpose,
    suggestedName: string | null,
  ): Promise<HostPathGrant | null> {
    return await TAURI_INVOKE("select_host_path", {
      purpose,
      suggested_name: suggestedName,
    });
  },
  /**
   * Issue a one-shot path grant for a file dropped onto the window by the OS.
   * Only `InstallOpen` purpose is accepted, and the path must exist, be absolute,
   * and carry a supported extension (.apk, .apks, .xapk, .apkm). This does not
   * bypass the grant model: the install command still consumes the grant normally.
   */
  async grantDroppedPath(path: string): Promise<HostPathGrant> {
    return await TAURI_INVOKE("grant_dropped_path", { path });
  },
  /**
   * Open the OS file manager at an artifact Droidsmith produced this session.
   * `path` must equal a save-dialog destination the backend itself issued; any
   * other renderer-supplied path is rejected, so the renderer can never drive an
   * open of an arbitrary location. The file manager is spawned detached.
   */
  async revealInFolder(path: string): Promise<null> {
    return await TAURI_INVOKE("reveal_in_folder", { path });
  },
  /**
   * Build a bounded, redacted support snapshot entirely on the local machine.
   * The payload deliberately excludes resolver paths and raw device targets.
   */
  async previewDiagnostics(): Promise<SupportPreview> {
    return await TAURI_INVOKE("preview_diagnostics");
  },
  /**
   * Generate a fresh redacted snapshot and persist it to the path retained by
   * the backend-owned native save dialog. No renderer-supplied bundle content is
   * accepted, so the backend remains the sole redaction boundary.
   */
  async saveDiagnostics(pathGrant: string): Promise<SavedResult> {
    return await TAURI_INVOKE("save_diagnostics", { path_grant: pathGrant });
  },
  /**
   * Remove only erasable diagnostic history: rotating crash logs and host-wide
   * recovery records. Per-device journals are intentionally preserved because
   * they back undo/recovery and are not disposable telemetry.
   */
  async wipeDiagnostics(confirmed: boolean): Promise<WipeResult> {
    return await TAURI_INVOKE("wipe_diagnostics", { confirmed });
  },
  async getDeviceInfo(target: DeviceTarget): Promise<DeviceInfo> {
    return await TAURI_INVOKE("get_device_info", { target });
  },
  async listWirelessServices(): Promise<ListWirelessServicesResult> {
    return await TAURI_INVOKE("list_wireless_services");
  },
  async pairWireless(
    request: WirelessPairRequest,
  ): Promise<WirelessCommandResult> {
    return await TAURI_INVOKE("pair_wireless", { request });
  },
  async connectWireless(
    request: WirelessConnectRequest,
  ): Promise<WirelessCommandResult> {
    return await TAURI_INVOKE("connect_wireless", { request });
  },
  async listPackages(
    target: DeviceTarget,
    filter: PackageFilter,
    userId: number,
  ): Promise<PackageListing> {
    return await TAURI_INVOKE("list_packages", { target, filter, userId });
  },
  /**
   * Lazily enrich one package row after it approaches the renderer viewport.
   * The domain service bounds concurrent pulls and validates a fresh APK
   * size/timestamp before consulting its process-local cache.
   */
  async getPackageMetadata(
    target: DeviceTarget,
    packageName: string,
    userId: number,
  ): Promise<AppPackageMetadata> {
    return await TAURI_INVOKE("get_package_metadata", {
      target,
      package: packageName,
      userId,
    });
  },
  /**
   * Enumerate Android users on a device so the renderer can offer an
   * explicit `--user` target for package workflows.
   */
  async listUsers(target: DeviceTarget): Promise<AndroidUser[]> {
    return await TAURI_INVOKE("list_users", { target });
  },
  /**
   * Import a profile through a one-shot native read grant and build a complete,
   * read-only device/user/package diff. Legacy v1 input is returned only as an
   * explicit migration candidate and cannot be applied as-is.
   */
  async inspectProfile(
    target: DeviceTarget,
    pathGrant: string,
  ): Promise<ProfilePreview> {
    return await TAURI_INVOKE("inspect_profile", {
      target,
      path_grant: pathGrant,
    });
  },
  /**
   * Validate and atomically export a current v2 profile through a purpose-
   * scoped native save grant. This is also the only GUI path that finalizes a
   * reviewed v1 migration.
   */
  async saveProfile(
    pathGrant: string,
    profile: Profile,
  ): Promise<HostArtifact> {
    return await TAURI_INVOKE("save_profile", {
      path_grant: pathGrant,
      profile,
    });
  },
  async listPacks(target: DeviceTarget, userId: number): Promise<PackListing> {
    return await TAURI_INVOKE("list_packs", { target, userId });
  },
  async planPack(request: PlanPackRequest): Promise<PlannedPack> {
    return await TAURI_INVOKE("plan_pack", { request });
  },
  /**
   * Synthesise an ADB action without running it. Pure: this is the
   * preview surface the confirmation dialog renders before the user
   * commits.
   */
  async planAction(request: ActionRequest): Promise<PlannedAction> {
    return await TAURI_INVOKE("plan_action", { request });
  },
  /**
   * Build one reviewed, reversible package-action plan for multiple packages.
   * Every item is bound to the same immutable device target, Android user, and
   * action kind; destructive or conditionally-reversible kinds stay on the
   * single-item path.
   */
  async planActionBatch(requests: ActionRequest[]): Promise<BatchActionPlan> {
    return await TAURI_INVOKE("plan_action_batch", { requests });
  },
  async planShellAction(
    request: PlanShellActionRequest,
  ): Promise<ShellActionPlan> {
    return await TAURI_INVOKE("plan_shell_action", { request });
  },
  /**
   * Apply a previously-planned action and record it in the per-device
   * journal. Returns the freshly-written journal entry.
   */
  async applyAction(plan: PlannedAction): Promise<ApplyActionResult> {
    return await TAURI_INVOKE("apply_action", { plan });
  },
  async applyActionBatch(batch: BatchActionPlan): Promise<BatchActionResult> {
    return await TAURI_INVOKE("apply_action_batch", { batch });
  },
  /**
   * Export a redacted package snapshot before a reviewed destructive batch.
   * The renderer supplies requested intents, while the backend captures all
   * device/package state and writes through a one-shot native path grant.
   */
  async exportRecoveryBaseline(
    target: DeviceTarget,
    userId: number,
    actions: BaselineActionInput[],
    pack: BaselinePack | null,
    pathGrant: string,
  ): Promise<HostArtifact> {
    return await TAURI_INVOKE("export_recovery_baseline", {
      target,
      userId,
      actions,
      pack,
      path_grant: pathGrant,
    });
  },
  /**
   * Load and compare a baseline without mutating the device. Returned plans are
   * canonical but remain inert until the renderer shows the diff and explicitly
   * submits individual plans through `apply_action`.
   */
  async inspectRecoveryBaseline(
    target: DeviceTarget,
    pathGrant: string,
  ): Promise<RecoveryBaselineDiff> {
    return await TAURI_INVOKE("inspect_recovery_baseline", {
      target,
      path_grant: pathGrant,
    });
  },
  async applyDeviceControl(
    target: DeviceTarget,
    argv: string[],
  ): Promise<ApplyActionResult> {
    return await TAURI_INVOKE("apply_device_control", { target, argv });
  },
  /**
   * Run a one-shot read-only shell command outside the webview thread and
   * stream progress/output through a Tauri channel. Mutations continue to use
   * the reviewed audited executor.
   */
  async shellRun(
    target: DeviceTarget,
    argv: string[],
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<string> {
    return await TAURI_INVOKE("shell_run", {
      target,
      argv,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Start one incremental Logcat process. Unexpected exits are retried by the
   * backend and surfaced as reconnect markers; the call completes only after
   * cancellation or an unrecoverable spawn/wait failure.
   */
  async streamLogcat(
    target: DeviceTarget,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<null> {
    return await TAURI_INVOKE("stream_logcat", {
      target,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Cancel a registered background operation. The runner observes this flag,
   * kills and reaps its child, and then emits a terminal cancellation event.
   */
  async cancelOperation(operationId: string): Promise<boolean> {
    return await TAURI_INVOKE("cancel_operation", {
      operation_id: operationId,
    });
  },
  /**
   * Persist the renderer's bounded Logcat buffer through a one-shot path grant.
   * The size limit keeps the IPC and host write bounded.
   */
  async saveLogcatExport(pathGrant: string, contents: string): Promise<string> {
    return await TAURI_INVOKE("save_logcat_export", {
      path_grant: pathGrant,
      contents,
    });
  },
  /**
   * List files in a remote directory on the device.
   */
  async listRemoteFiles(
    target: DeviceTarget,
    remotePath: string,
  ): Promise<RemoteListing> {
    return await TAURI_INVOKE("list_remote_files", {
      target,
      remote_path: remotePath,
    });
  },
  /**
   * Validate a structured file mutation and return the exact argv that will be
   * journaled and executed after the renderer presents its confirmation review.
   */
  async planRemoteFileMutation(
    request: RemoteFileMutationRequest,
  ): Promise<RemoteFileMutationPlan> {
    return await TAURI_INVOKE("plan_remote_file_mutation", { request });
  },
  /**
   * Rebuild and execute a reviewed device-side file mutation. The renderer
   * cannot supply argv: it submits only structured paths and the backend
   * regenerates the canonical mkdir/mv/rm command before writing the intent.
   */
  async applyRemoteFileMutation(
    target: DeviceTarget,
    request: RemoteFileMutationRequest,
    confirmed: boolean,
  ): Promise<ApplyActionResult> {
    return await TAURI_INVOKE("apply_remote_file_mutation", {
      target,
      request,
      confirmed,
    });
  },
  /**
   * Push a local file to the device.
   */
  async pushFile(
    target: DeviceTarget,
    pathGrant: string,
    remotePath: string,
    confirmed: boolean,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<ApplyActionResult> {
    return await TAURI_INVOKE("push_file", {
      target,
      path_grant: pathGrant,
      remote_path: remotePath,
      confirmed,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Pull a remote file from the device.
   */
  async pullFile(
    target: DeviceTarget,
    remotePath: string,
    pathGrant: string,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<HostArtifact> {
    return await TAURI_INVOKE("pull_file", {
      target,
      remote_path: remotePath,
      path_grant: pathGrant,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Inspect the package's default APK export and deprecated data-backup
   * capabilities. This is read-only and scoped to one Android user.
   */
  async preflightPackageBackup(
    target: DeviceTarget,
    packageName: string,
    userId: number,
  ): Promise<PackageBackupPreflight> {
    return await TAURI_INVOKE("preflight_package_backup", {
      target,
      package: packageName,
      userId,
    });
  },
  /**
   * Export every base/split APK plus a versioned evidence manifest to one
   * atomically-installed ZIP. This is the dependable default package backup.
   */
  async exportPackageApks(
    target: DeviceTarget,
    packageName: string,
    userId: number,
    pathGrant: string,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<PackageExportResult> {
    return await TAURI_INVOKE("export_package_apks", {
      target,
      package: packageName,
      userId,
      path_grant: pathGrant,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Advanced-only deprecated `adb backup` path. The produced `.ab` is forced
   * uncompressed, structurally inspected, and packaged with a manifest. The
   * result reports detected entries, never verified restorability.
   */
  async backupPackage(
    target: DeviceTarget,
    packageName: string,
    userId: number,
    pathGrant: string,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<PackageExportResult> {
    return await TAURI_INVOKE("backup_package", {
      target,
      package: packageName,
      userId,
      path_grant: pathGrant,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Capture an opaque Android bugreport only after a dedicated privacy
   * acknowledgement. The immutable target and one-shot native path grant are
   * revalidated before the long-running ADB process begins.
   */
  async captureBugreport(
    target: DeviceTarget,
    pathGrant: string,
    privacyConfirmed: boolean,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<BugreportCaptureResult> {
    return await TAURI_INVOKE("capture_bugreport", {
      target,
      path_grant: pathGrant,
      privacy_confirmed: privacyConfirmed,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Get network connections from the device using `ss -tunp`.
   */
  async listNetworkConnections(
    target: DeviceTarget,
  ): Promise<NetworkConnection[]> {
    return await TAURI_INVOKE("list_network_connections", { target });
  },
  /**
   * List runtime permissions for a package.
   */
  async listPermissions(
    target: DeviceTarget,
    packageName: string,
  ): Promise<PermissionInfo[]> {
    return await TAURI_INVOKE("list_permissions", {
      target,
      package: packageName,
    });
  },
  /**
   * Grant or revoke a runtime permission.
   */
  async setPermission(
    target: DeviceTarget,
    packageName: string,
    permission: string,
    grant: boolean,
    userId: number,
  ): Promise<ApplyActionResult> {
    return await TAURI_INVOKE("set_permission", {
      target,
      package: packageName,
      permission,
      grant,
      userId,
    });
  },
  /**
   * Get process list from a device. Uses `ps -A -o PID,USER,VSZ,RSS,%CPU,NAME`
   * for a structured snapshot.
   */
  async listProcesses(target: DeviceTarget): Promise<ProcessInfo[]> {
    return await TAURI_INVOKE("list_processes", { target });
  },
  /**
   * Take a screenshot on the device and pull it to a local path.
   */
  async takeScreenshot(
    target: DeviceTarget,
    pathGrant: string,
  ): Promise<HostArtifact> {
    return await TAURI_INVOKE("take_screenshot", {
      target,
      path_grant: pathGrant,
    });
  },
  /**
   * Locate the scrcpy binary on the system. Returns the path if found.
   */
  async locateScrcpy(): Promise<string | null> {
    return await TAURI_INVOKE("locate_scrcpy");
  },
  /**
   * Probe the installed scrcpy build and the selected device's reported video
   * encoders. Results are cached against both the binary fingerprint and the
   * immutable device target, so an upgraded/replaced executable is never
   * trusted through stale capability data.
   */
  async scrcpyCapabilities(target: DeviceTarget): Promise<ScrcpyCapabilities> {
    return await TAURI_INVOKE("scrcpy_capabilities", { target });
  },
  /**
   * Launch scrcpy for a device. Fire-and-forget: we spawn the process
   * and track it so the renderer can poll or stop the session.
   */
  async launchScrcpy(
    request: LaunchScrcpyRequest,
    pathGrant: string | null,
  ): Promise<ScrcpySession> {
    return await TAURI_INVOKE("launch_scrcpy", {
      request,
      path_grant: pathGrant,
    });
  },
  async scrcpySessionStatus(sessionId: number): Promise<ScrcpySession> {
    return await TAURI_INVOKE("scrcpy_session_status", {
      session_id: sessionId,
    });
  },
  async stopScrcpy(sessionId: number): Promise<ScrcpySession> {
    return await TAURI_INVOKE("stop_scrcpy", { session_id: sessionId });
  },
  /**
   * Install an APK or split-package archive on a device. Single APKs retain the
   * direct `adb install -r` path; APKS/XAPK/APKM archives are committed through
   * an atomic PackageInstaller session.
   */
  async installApk(
    target: DeviceTarget,
    pathGrant: string,
    options: InstallOptions,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<InstallPackageResult> {
    return await TAURI_INVOKE("install_apk", {
      target,
      path_grant: pathGrant,
      options,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  /**
   * Pull an APK from the device to a local path.
   */
  async extractApk(
    target: DeviceTarget,
    remotePath: string,
    pathGrant: string,
    operationId: string,
    onEvent: TAURI_CHANNEL<OperationEvent>,
  ): Promise<HostArtifact> {
    return await TAURI_INVOKE("extract_apk", {
      target,
      remote_path: remotePath,
      path_grant: pathGrant,
      operation_id: operationId,
      on_event: onEvent,
    });
  },
  async journalList(serial: string): Promise<JournalEntry[]> {
    return await TAURI_INVOKE("journal_list", { serial });
  },
  /**
   * Undo entry `entry_id` in `serial`'s journal. Returns the new
   * undo-entry. Fails if the original action is irreversible
   * (unverified uninstall, clear-data, force-stop).
   */
  async journalUndo(
    target: DeviceTarget,
    entryId: number,
  ): Promise<JournalEntry> {
    return await TAURI_INVOKE("journal_undo", { target, entry_id: entryId });
  },
  /**
   * Undo every still-active successful item from one backend-issued batch.
   * Reversibility is proven for the complete remaining set before the first
   * inverse runs; device-level failures are then reported per package without
   * hiding successful inverses.
   */
  async journalUndoBatch(
    target: DeviceTarget,
    batchId: string,
  ): Promise<BatchActionResult> {
    return await TAURI_INVOKE("journal_undo_batch", { target, batchId });
  },
  /**
   * Load quirks from the bundled resource directory and match against the
   * failure context.
   * Returns `Some(quirk)` if a rule applies, `None` if the raw error
   * should be shown as-is.
   */
  async explainFailure(req: ExplainFailureRequest): Promise<Quirk | null> {
    return await TAURI_INVOKE("explain_failure", { req });
  },
  /**
   * Locate the fastboot binary on the system.
   */
  async locateFastboot(): Promise<string | null> {
    return await TAURI_INVOKE("locate_fastboot");
  },
  /**
   * List devices visible to fastboot.
   */
  async listFastbootDevices(): Promise<FastbootDevice[]> {
    return await TAURI_INVOKE("list_fastboot_devices");
  },
  /**
   * Query a fastboot variable.
   */
  async fastbootGetvar(serial: string, key: string): Promise<string> {
    return await TAURI_INVOKE("fastboot_getvar", { serial, key });
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type ActionContext = {
  confirmation_source?: ConfirmationSource;
  permission?: string | null;
  shell_argv?: string[];
  /**
   * Set by the trusted backend only after it revalidates and accepts an
   * explicit renderer acknowledgement for an unauthenticated transport.
   */
  transport_override?: DeviceTransportKind | null;
  /**
   * Backend-only state carried from a verified uninstall journal row into
   * its `install-existing` inverse.
   */
  restore_enabled_state?: boolean | null;
  /**
   * Backend-issued identifier shared by every item in one reviewed batch.
   * The renderer may display this value but cannot assign it through the
   * single-action planner/apply boundary.
   */
  batch_id?: string | null;
};
export type ActionKind =
  /**
   * `pm disable-user --user 0 <pkg>` — reversible with `pm enable`.
   */
  | "disable"
  /**
   * `pm enable <pkg>` — reverses Disable.
   */
  | "enable"
  /**
   * Android 15+ `pm archive` keeps user data while removing APK/cache.
   */
  | "archive"
  /**
   * Android 15+ `pm request-unarchive` asks the responsible installer to
   * restore an archived package.
   */
  | "request_unarchive"
  /**
   * `pm uninstall --user 0 <pkg>` — effectively permanent for the
   * current user; the APK remains in `/system/` (system apps) but
   * is removed from `/data/app/` (user apps).
   */
  | "uninstall_for_user"
  /**
   * Backend-only inverse for a verified retained system package.
   * `cmd package install-existing` is followed by an explicit restoration
   * and verification of the prior enabled state.
   */
  | "restore_existing_for_user"
  /**
   * `pm clear <pkg>` — wipes the package's data and cache.
   */
  | "clear_data"
  /**
   * `am force-stop <pkg>` — non-destructive; included for symmetry.
   */
  | "force_stop"
  /**
   * `pm grant --user <id> <pkg> <permission>`.
   */
  | "grant_permission"
  /**
   * `pm revoke --user <id> <pkg> <permission>`.
   */
  | "revoke_permission"
  /**
   * A reviewed arbitrary shell mutation. Read-only shell commands use the
   * separate `shell_run` path and never enter the mutation journal.
   */
  | "shell";
export type ActionRequest = {
  serial: string;
  /**
   * Immutable live target captured from `list_devices`. Legacy journal
   * rows deserialize to an invalid default and must be rebound by the
   * explicit undo request before execution.
   */
  target?: DeviceTarget;
  package: string;
  kind: ActionKind;
  /**
   * Android user id the action targets (`pm --user`). Defaults to `0`
   * (the primary/owner user) so legacy journal entries and older
   * callers that predate multi-user targeting deserialize unchanged.
   */
  user_id?: number;
  /**
   * Structured provenance for actions planned from a debloat pack. This is
   * persisted in the journal, including any explicit compatibility override.
   */
  pack_context?: PackActionContext | null;
  /**
   * Operation-specific canonical data and the UI/CLI confirmation source.
   */
  context?: ActionContext;
};
export type AdbHealth = {
  server_status_supported: boolean;
  client_version: string | null;
  server_version: string | null;
  server_build: string | null;
  usb_backend: string | null;
  mdns_backend: string | null;
  mdns_enabled: boolean | null;
  mdns_check: string | null;
  burst_mode: boolean | null;
  recommended_for_wifi_v2: boolean;
  wifi_v2_state: WifiV2State;
  wifi_v2_devices: string[];
  warning: string | null;
  platform_tools: PlatformToolsAssessment;
};
export type AdbRecoveryOutcome =
  | "pending"
  | "succeeded"
  | "failed"
  | "cancelled";
export type AdbRecoveryRecord = {
  schema_version: number;
  operation_id: string;
  operation: string;
  confirmation_source: string;
  outcome: AdbRecoveryOutcome;
  started_at: string;
  completed_at: string | null;
  commands: string[][];
  health_before: AdbHealth | null;
  health_after: AdbHealth | null;
  failure: string | null;
};
export type AdbRecoveryResult = {
  record: AdbRecoveryRecord;
  record_path: string;
};
/**
 * Result of resolving the `adb` binary on this machine.
 */
export type AdbResolution = {
  path: string | null;
  source: ResolveSource;
  version: string | null;
  compatibility: PlatformToolsAssessment;
};
export type AndroidUser = {
  /**
   * Numeric user id passed to `pm --user`.
   */
  id: number;
  /**
   * Human-readable name, e.g. `Owner`, `Work profile`.
   */
  name: string;
  /**
   * True when `pm list users` reports the user as running.
   */
  running: boolean;
  /**
   * True for the foreground user (resolved via `am get-current-user`,
   * falling back to the `pm list users` "(current)" marker).
   */
  current: boolean;
};
export type AppPackage = {
  /**
   * Application package id, e.g. `com.android.chrome`.
   */
  package: string;
  /**
   * True when found via `-e`, false when only `-d`.
   */
  enabled: boolean;
  /**
   * Heuristic: an app is "system" if its APK is under `/system/`,
   * `/product/`, `/vendor/`, `/apex/`, or `/system_ext/`. Mirrors
   * the heuristic Android Settings itself uses.
   */
  system: boolean;
  /**
   * Absolute APK path on the device, when `-f` produced one.
   */
  apk_path: string | null;
  /**
   * UID owning the package, when `-U` produced one.
   */
  uid: number | null;
  /**
   * Installer source package id, when `-i` produced one. Used to
   * surface "Installed from Play Store" vs ApkMirror / sideload.
   */
  installer: string | null;
  /**
   * True when Android 15+ has removed the APK/cache while retaining user
   * data and installer metadata for a later unarchive request.
   */
  archived: boolean;
  /**
   * True when PackageManager still retains this package's user data for the
   * selected Android user (`pm list packages -u`) but it is neither
   * installed nor archived — an uninstalled-with-data remnant whose leftover
   * data can be fully purged.
   */
  retained: boolean;
};
export type AppPackageMetadata = {
  package: string;
  label: string | null;
  icon_data_uri: string | null;
  cache_hit: boolean;
};
/**
 * Applied action — the journal record. `stdout`/`stderr` are kept so
 * support tickets can include the raw response.
 */
export type AppliedAction = {
  plan: PlannedAction;
  stdout: string;
  before_state?: string;
  after_state?: string;
  /**
   * ISO-8601 UTC timestamp.
   */
  applied_at: string;
};
export type ApplyActionResult = {
  entry: JournalEntry;
  /**
   * Raw output is returned only to the initiating view and is excluded from
   * the persisted journal, which carries the redacted/bounded copy.
   */
  stdout: string;
};
export type BackupCapability =
  | "apk_export"
  | "legacy_data_eligible"
  | "legacy_data_blocked"
  | "legacy_data_unknown";
export type BaselineActionInput = { package: string; kind: ActionKind };
export type BaselineCompatibility = {
  device_identity_matches: boolean;
  build_fingerprint_matches: boolean;
  android_user_available: boolean;
  current_device_identity_sha256: string;
  current_build_fingerprint: string;
};
export type BaselineDevice = {
  identity_sha256: string;
  build_fingerprint: string;
};
export type BaselineDiffRow = {
  package: string;
  baseline_present: boolean;
  baseline_enabled: boolean | null;
  live_present: boolean;
  live_enabled: boolean | null;
  requested_action: ActionKind;
  status: BaselineDiffStatus;
  reason_code: string | null;
  reason: string;
};
export type BaselineDiffStatus =
  | "ready"
  | "already_matches"
  | "drifted"
  | "skipped";
export type BaselinePack = { id: string; revision: number };
export type BaselinePackage = {
  package: string;
  present: boolean;
  enabled: boolean | null;
  system: boolean | null;
  requested_action: ActionKind;
  undo_plan: BaselineUndoPlan | null;
};
export type BaselineUndoPlan = { kind: ActionKind; user_id: number };
export type BatchActionItemResult = {
  package: string;
  entry: JournalEntry | null;
  stdout: string;
  error: string | null;
};
export type BatchActionPlan = { plans: PlannedAction[]; description: string };
export type BatchActionResult = {
  batch_id: string;
  items: BatchActionItemResult[];
};
export type BatteryInfo = {
  level: number | null;
  status: string | null;
  temperature: number | null;
};
export type BugreportCaptureResult = {
  report: HostArtifact;
  sidecar: HostArtifact;
  captured_at: string;
};
/**
 * Generic Tauri-command error envelope so the JS side gets the same
 * shape regardless of whether the underlying failure was a transport
 * error or a filesystem error from the journal.
 */
export type CommandError = {
  /**
   * Stable string code for client-side branching (e.g. "adb_not_found").
   */
  code: string;
  message: string;
};
export type CompatibilityCheck = {
  field: string;
  status: CompatibilityStatus;
  expected: string[];
  actual: string | null;
};
export type CompatibilityStatus = "compatible" | "unknown" | "mismatch";
export type ConfirmationSource =
  | "unspecified"
  | "internal"
  | "apps_preview"
  | "debloat_preview"
  | "permission_toggle"
  | "console_review"
  | "device_control"
  | "cli_apply"
  | "profile_preview"
  | "file_manager_review"
  | "journal_undo"
  | "recovery_baseline";
/**
 * A single connected device, as seen by `adb devices -l`.
 */
export type Device = {
  /**
   * Hardware serial or `host:port` for TCP/wireless devices. Stable
   * per device; survives reboots over USB.
   */
  serial: string;
  state: DeviceState;
  /**
   * Optional `model:` field from `adb devices -l`. Not all devices /
   * states populate it.
   */
  model: string | null;
  /**
   * Optional `product:` field. Same caveat as `model`.
   */
  product: string | null;
  /**
   * Optional `device:` field — the kernel device codename.
   */
  device: string | null;
  /**
   * Build fingerprint captured while this connection target is prepared.
   */
  build_fingerprint: string | null;
  /**
   * Optional `transport_id:`. Stable for the life of the adb-server
   * session.
   */
  transport_id: number | null;
  /**
   * Process-local generation assigned when this exact ADB transport
   * first appears. A disconnect observed by Droidsmith retires the
   * generation, so a later reconnect cannot reuse a stale UI target.
   */
  connection_generation: number;
  /**
   * Trust classification derived from USB identity or process-local
   * wireless connection provenance. An address alone is never enough to
   * claim Android 11+ TLS Wireless Debugging.
   */
  transport_kind: DeviceTransportKind;
  /**
   * True if the device serial parses as a `host:port` (wireless)
   * rather than a hardware serial.
   */
  wireless: boolean;
};
export type DeviceInfo = {
  serial: string;
  model: string | null;
  manufacturer: string | null;
  android_version: string | null;
  sdk_level: string | null;
  build_fingerprint: string | null;
  security_patch: string | null;
  hardware_serial: string | null;
  battery: BatteryInfo | null;
  storage: StorageInfo | null;
  wifi_ip: string | null;
};
export type DeviceLifecycleEvent =
  | {
      kind: "snapshot";
      result: ListDevicesResult;
      health: AdbHealth | null;
      observed_at: string;
    }
  | { kind: "error"; message: string; observed_at: string };
export type DeviceState =
  /**
   * `device` — fully authorized.
   */
  | "device"
  /**
   * `unauthorized` — user hasn't tapped "Allow USB debugging" yet.
   */
  | "unauthorized"
  /**
   * `offline` — adb-server lost contact (cable dropout, sleep).
   */
  | "offline"
  /**
   * `recovery` — booted into recovery mode.
   */
  | "recovery"
  /**
   * `bootloader` — in fastboot/bootloader. Not common from
   * `adb devices` but documented.
   */
  | "bootloader"
  /**
   * `sideload` — sideload mode.
   */
  | "sideload"
  /**
   * `no permissions` — udev rules missing on Linux. We surface this
   * distinctly so the UI can show a fix-it tip.
   */
  | "no_permissions"
  /**
   * Anything we don't recognise. We keep the raw string so support
   * requests can include it without losing fidelity.
   */
  | { other: string };
/**
 * Immutable device identity captured by the renderer before an operation.
 *
 * The serial remains useful for display/journal partitioning, but execution
 * prefers `transport_id` and verifies this generation plus the advertised
 * metadata immediately before talking to the device.
 */
export type DeviceTarget = {
  serial: string;
  transport_id: number | null;
  connection_generation: number;
  model: string | null;
  product: string | null;
  device: string | null;
  build_fingerprint: string | null;
  transport_kind?: DeviceTransportKind;
  /**
   * Explicit renderer acknowledgement for one selected connection. This is
   * authorization metadata, not identity, and is checked only after the
   * live target's independently-derived transport kind is revalidated.
   */
  untrusted_transport_override?: boolean;
};
export type DeviceTransportKind =
  | "usb"
  | "tls_wifi"
  | "legacy_tcp"
  | "unknown_tcp";
/**
 * Request shape for [`explain_failure`].
 */
export type ExplainFailureRequest = {
  manufacturer: string | null;
  rom: string | null;
  package_id: string | null;
  raw_error: string | null;
};
export type ExportMode = "apk_export" | "legacy_data";
export type ExportedArtifact = {
  name: string;
  role: string;
  size_bytes: number;
  sha256: string;
};
export type FastbootDevice = {
  serial: string;
  mode: string;
  product: string | null;
  parse_error?: string | null;
};
export type FindingSeverity = "info" | "warning" | "error";
export type HashedDeviceIdentity = {
  device_identity_sha256: string;
  build_identity_sha256: string | null;
};
export type Heartbeat = {
  /**
   * Droidsmith app version (`CARGO_PKG_VERSION`).
   */
  version: string;
  /**
   * Operating system family + version + arch.
   */
  os: OsInfo;
  /**
   * Tauri framework version this build links against.
   */
  tauri_version: string;
  /**
   * Rust MSRV declared in `Cargo.toml`. Useful for bug reports.
   */
  rust_version: string;
  /**
   * Where the user's persisted state lives (journal, settings, logs).
   */
  app_data_dir: string | null;
  /**
   * ADB binary resolution + source + version.
   */
  adb: AdbResolution;
};
/**
 * Metadata returned to the renderer only after a host artifact has passed
 * validation and been atomically installed at its final path.
 */
export type HostArtifact = {
  local_path: string;
  size_bytes: number;
  sha256: string;
};
export type HostDoctorAdb = {
  resolved: boolean;
  source: ResolveSource;
  version: string | null;
  query_succeeded: boolean;
  client_version: string | null;
  server_version: string | null;
  compatibility: PlatformToolsAssessment;
};
export type HostDoctorReport = {
  scanned_at: string;
  platform: string;
  adb: HostDoctorAdb;
  device_state_counts: Partial<{ [key in string]: number }>;
  findings: HostFinding[];
  privacy: string[];
};
export type HostFinding = {
  code: string;
  severity: FindingSeverity;
  title: string;
  summary: string;
  evidence: string[];
  remediation: string[];
  official_url: string;
};
export type HostPathGrant = {
  id: string;
  purpose: HostPathPurpose;
  local_path: string;
};
/**
 * A native-dialog purpose is also the authorization scope. Read grants can
 * never reach write commands (or another read command), and vice versa.
 */
export type HostPathPurpose =
  | "diagnostics_save"
  | "bugreport_save"
  | "scrcpy_record_save"
  | "logcat_save"
  | "package_export_save"
  | "backup_save"
  | "screenshot_save"
  | "pull_save"
  | "extract_apk_save"
  | "recovery_baseline_save"
  | "profile_save"
  | "settings_export"
  | "layout_export_save"
  | "push_open"
  | "install_open"
  | "recovery_baseline_open"
  | "profile_open";
export type InstallFailure = {
  code: string;
  cause: string;
  remedy: string;
  suggested_override: SuggestedInstallOverride | null;
  raw_output: string;
};
/**
 * The install strategy actually used, recorded in the operation audit so a
 * fallback is never silent.
 */
export type InstallMode =
  /**
   * A standard `adb install` (or the split-session path for archives).
   */
  | "normal"
  /**
   * `adb install --incremental` succeeded.
   */
  | "incremental"
  /**
   * Incremental was requested but unsupported here, so a normal install ran.
   */
  | "incremental_unsupported";
export type InstallOptions = {
  allow_downgrade?: boolean;
  bypass_low_target_sdk_block?: boolean;
  override_confirmed?: boolean;
  /**
   * Opt-in: begin a single-APK install before all bytes transfer via
   * `adb install --incremental`, falling back to a normal install when the
   * device or platform-tools do not support Incremental FS.
   */
  incremental?: boolean;
};
export type InstallPackageResult = {
  succeeded: boolean;
  source_kind: InstallSourceKind;
  install_mode: InstallMode;
  file_count: number;
  total_bytes: number;
  output: string;
  failure: InstallFailure | null;
  audit_id: string;
  /**
   * A fresh one-shot grant for the same native-dialog-selected source is
   * issued only when the backend recommends an explicit override retry.
   */
  retry_path_grant: string | null;
};
export type InstallSourceKind = "apk" | "apks" | "xapk" | "apkm";
export type JournalEntry = {
  /**
   * Monotonic per-file id. Unique within a journal file.
   */
  id: number;
  applied: AppliedAction;
  /**
   * `Some(undo_entry_id)` if a subsequent entry reverses this one
   * via [`record_undo`].
   */
  undone_by: number | null;
  /**
   * `Some(undone_entry_id)` if this entry was created to undo an
   * earlier one. Lets the UI render an "Undo of #N" hint.
   */
  undoes: number | null;
  /**
   * Durable lifecycle for this operation. Missing on legacy rows, which
   * were only written after success and therefore deserialize as succeeded.
   */
  outcome?: JournalOutcome;
  /**
   * Redacted terminal failure or recovery detail. Pending and successful
   * entries keep this empty.
   */
  failure?: string | null;
};
export type JournalOutcome = "pending" | "succeeded" | "failed" | "interrupted";
export type KeyboardMode = "default" | "sdk" | "uhid" | "aoa" | "disabled";
export type LaunchScrcpyRequest = {
  serial: string;
  target: DeviceTarget;
  max_size: number | null;
  bit_rate: string | null;
  no_audio: boolean;
  keyboard_mode: string | null;
  video_codec: string | null;
  video_encoder: string | null;
  turn_screen_off: boolean;
  stay_awake: boolean;
  show_touches: boolean;
  flex_display: boolean;
  keep_active: boolean;
};
/**
 * One node of a `uiautomator dump` UI hierarchy, flattened with its nesting
 * `depth` so the renderer can indent it. Malformed structure yields a node
 * with `parse_error` set instead of being silently dropped.
 */
export type LayoutNode = {
  depth: number;
  index: string;
  class: string;
  package: string;
  text: string;
  content_desc: string;
  resource_id: string;
  bounds: string;
  clickable: boolean;
  enabled: boolean;
  parse_error?: string | null;
};
/**
 * A read-only snapshot of the current on-screen UI hierarchy plus the raw
 * dump so the renderer can export it verbatim.
 */
export type LayoutSnapshot = {
  nodes: LayoutNode[];
  node_count: number;
  raw_xml: string;
};
export type LegacyContent = "app_data_entries_detected" | "no_app_data_entries";
export type LegacyEligibilityEvidence = {
  device_sdk: number | null;
  target_sdk: number | null;
  debuggable: boolean | null;
  allow_backup: boolean | null;
  reason: string;
};
export type LegacyMirrorPresetInput = {
  deviceIdentity: string;
  rawValue: string;
};
export type LegacySettingsImport = {
  language: string | null;
  mirrorPresets?: LegacyMirrorPresetInput[];
};
/**
 * Outcome envelope for `list_devices`. We surface adb-not-found as a
 * structured success-with-zero-devices + an `adb_resolved=false` flag
 * rather than an Err, because "no adb installed" is a normal first-run
 * state, not a runtime fault.
 */
export type ListDevicesResult = {
  adb_resolved: boolean;
  adb_path: string | null;
  devices: Device[];
};
export type ListWirelessServicesResult = {
  adb_resolved: boolean;
  adb_path: string | null;
  services: WirelessAdbService[];
};
/**
 * Minimum severity a Logcat query preset matches, using adb's single-letter
 * level codes so the renderer can reuse its existing `V D I W E F` ladder.
 */
export type LogcatLevel = "V" | "D" | "I" | "W" | "E" | "F";
/**
 * A reusable, versioned Logcat filter. Only the query definition is persisted;
 * captured log lines never enter the store.
 */
export type LogcatQuery = {
  id: string;
  name: string;
  tagFilter?: string;
  messageFilter?: string;
  pidFilter?: string;
  packageFilter?: string;
  processFilter?: string;
  minLevel: LogcatLevel;
  maxAgeSeconds?: number | null;
  useRegex?: boolean;
  negateTag?: boolean;
  negateMessage?: boolean;
  negatePid?: boolean;
  negatePackage?: boolean;
  negateProcess?: boolean;
};
export type LogcatQueryLibrary = {
  version: string;
  global: LogcatQuery[];
  device: LogcatQuery[];
};
export type LogcatQueryScope = "global" | "device";
export type MirrorPreset = {
  maxSize: string;
  bitRate: string;
  noAudio: boolean;
  recording: boolean;
  keyboardMode: KeyboardMode;
  videoCodec: VideoCodec;
  videoEncoder: string;
  turnScreenOff: boolean;
  stayAwake: boolean;
  showTouches: boolean;
  flexDisplay?: boolean;
  keepActive?: boolean;
};
export type Mitigation =
  /**
   * Suggest re-running the action with a different `ActionKind`.
   * Most common case: "pm disable failed → try pm uninstall --user 0".
   */
  | { kind: "try_alternative_action"; suggest_kind: string; rationale: string }
  /**
   * Surface a doc link or workaround the user has to perform off-app.
   */
  | { kind: "documentation"; url: string; note: string }
  /**
   * No automated fix; this quirk is informational only.
   */
  | { kind: "none" };
export type NetworkConnection = {
  state: string;
  protocol: string;
  local_addr: string;
  remote_addr: string;
  process: string | null;
  parse_error?: string | null;
};
export type OperationEvent = {
  operation_id: string;
  kind: OperationEventKind;
  stream?: string | null;
  chunk?: string | null;
  message?: string | null;
  elapsed_ms?: number | null;
  attempt?: number | null;
};
export type OperationEventKind =
  | "started"
  | "output"
  | "progress"
  | "reconnecting"
  | "finished"
  | "cancelled";
export type OsInfo = { family: string; version: string; arch: string };
export type Pack = {
  /**
   * Stable machine identifier; never derived from the display name.
   */
  id?: string;
  /**
   * Monotonic content revision for audit records and cached assessments.
   */
  revision?: number;
  /**
   * Human-friendly title shown in the pack picker.
   */
  name: string;
  /**
   * Bump on every breaking change; the loader checks
   * `version == "1"` for now and refuses to load future revs.
   */
  version: string;
  /**
   * One-paragraph description shown under the title.
   */
  description: string;
  /**
   * Device and Android-user constraints assessed before the picker and
   * revalidated immediately before a pack plan is created.
   */
  targets?: PackTargets;
  /**
   * The packages this pack offers to remove.
   */
  packages: PackEntry[];
  /**
   * Free-form attribution / licence (e.g. "Adapted from UAD-NG, GPL-3.0").
   * Optional, but pack-lint warns when missing for community packs.
   */
  attribution?: string | null;
  /**
   * Structured source/license information retained in every operation plan.
   */
  provenance?: PackProvenance;
};
export type PackActionContext = {
  pack_id: string;
  revision: number;
  provenance_source: string;
  provenance_license: string;
  compatibility_status: string;
  override_accepted: boolean;
};
export type PackAssessment = {
  status: CompatibilityStatus;
  override_required: boolean;
  checks: CompatibilityCheck[];
  entries: PackEntryAssessment[];
};
export type PackCandidate = { pack: Pack; assessment: PackAssessment };
export type PackEntry = {
  /**
   * Android package identifier.
   */
  id: string;
  /**
   * Severity tier; matches UAD-NG semantics.
   */
  removal: RemovalLevel;
  /**
   * What the package does, in user-facing language. Pack-lint
   * requires this — no anonymous entries.
   */
  description: string;
  /**
   * Optional list of package IDs whose removal forces this one off
   * too. Surfaced in the diff preview.
   */
  depends_on?: string[];
  /**
   * Optional list of package IDs that need this one to stay enabled.
   * Warned about during preview.
   */
  needed_by?: string[];
  /**
   * Free-form tags for search/grouping ("ads", "telemetry", "bloat",
   * "vendor-locked").
   */
  labels?: string[];
};
export type PackEntryAssessment = {
  id: string;
  status: PackEntryStatus;
  detail: string | null;
};
export type PackEntryStatus = "ready" | "missing" | "unsupported";
/**
 * Result of enumerating bundled packs: the healthy packs plus per-file
 * errors for any that failed. A broken file no longer disappears
 * silently — it surfaces as an error the user can act on.
 */
export type PackListing = { packs: PackCandidate[]; errors: PackLoadError[] };
/**
 * List all debloat packs from the app's `packs/` resource directory.
 * A bundled pack file that failed to load, with a stable code and a
 * human-readable message the UI can show and the user can copy.
 */
export type PackLoadError = {
  /**
   * File name (not full path — no host paths leak to the renderer).
   */
  file: string;
  /**
   * Stable code: `pack_read`, `pack_parse`, `pack_validate`, or
   * `pack_duplicate_id`.
   */
  code: string;
  message: string;
};
export type PackProvenance = { source: string; license: string };
export type PackTargets = {
  /**
   * Manufacturer strings as reported by `ro.product.manufacturer`.
   */
  manufacturer?: string[];
  /**
   * ROM family, e.g. ["oneui", "stock"]. Free-form, matched
   * case-insensitively.
   */
  rom?: string[];
  /**
   * Optional case-insensitive model substrings.
   */
  model?: string[];
  /**
   * Optional case-insensitive build-fingerprint substrings.
   */
  build_fingerprint?: string[];
  /**
   * Inclusive minimum Android API level (e.g. 30 for Android 11).
   */
  android_min?: number | null;
  /**
   * Inclusive maximum Android API level.
   */
  android_max?: number | null;
  /**
   * Explicit Android-user policy. Packs must never silently inherit user 0.
   */
  user_scope?: UserScope;
};
export type PackageArchiveCapability = {
  supported: boolean;
  api_level: number | null;
  reason: string;
};
export type PackageBackupPreflight = {
  package: string;
  android_user: number;
  default_capability: BackupCapability;
  legacy_capability: BackupCapability;
  apk_paths: string[];
  evidence: LegacyEligibilityEvidence;
};
export type PackageExportManifest = {
  format: string;
  schema_version: number;
  created_at: string;
  mode: ExportMode;
  package: string;
  android_user: number;
  device: HashedDeviceIdentity;
  eligibility: LegacyEligibilityEvidence;
  legacy_content: LegacyContent | null;
  artifacts: ExportedArtifact[];
};
export type PackageExportResult = {
  artifact: HostArtifact;
  manifest: PackageExportManifest;
};
export type PackageFilter =
  | "all"
  | "user"
  | "system"
  | "enabled"
  | "disabled"
  | "archived"
  | "retained";
export type PackageListing = {
  packages: AppPackage[];
  archive: PackageArchiveCapability;
};
export type PermissionInfo = { permission: string; granted: boolean };
export type PlanPackRequest = {
  target: DeviceTarget;
  user_id: number;
  pack_id: string;
  revision: number;
  selected: string[];
  override_compatibility?: boolean;
};
export type PlanShellActionRequest = { target: DeviceTarget; argv: string[] };
/**
 * Synthesised plan. The `args` field is exactly what the action will
 * pass to `adb shell` — no further interpolation happens at apply
 * time. `description` is human-readable for the confirmation dialog.
 */
export type PlannedAction = {
  request: ActionRequest;
  args: string[];
  description: string;
  /**
   * Stable identifier carried by the write-ahead intent and terminal row.
   */
  incident_id?: string;
  /**
   * Snapshot captured immediately before the durable write-ahead intent.
   */
  before_state?: string;
};
export type PlannedPack = {
  pack_id: string;
  revision: number;
  assessment: PackAssessment;
  selected_ids: string[];
  plans: PlannedAction[];
  skipped: PackEntryAssessment[];
};
export type PlatformToolsAssessment = {
  status: PlatformToolsStatus;
  rationale: string;
  recommended_version: string;
  warning_below_version: string;
  policy_reviewed_on: string;
  source_url: string;
};
export type PlatformToolsStatus = "supported" | "warn" | "blocked";
export type ProcessInfo = {
  pid: number;
  user: string;
  vsz_kb: number;
  rss_kb: number;
  name: string;
  parse_error?: string | null;
};
export type Profile = {
  name: string;
  version: string;
  description?: string;
  device?: ProfileDeviceMatch;
  user?: ProfileUserTarget;
  actions: ProfileAction[];
};
export type ProfileAction = {
  kind: ActionKind;
  package: string;
  note?: string;
};
export type ProfileDeviceMatch = {
  require_serial_prefix?: string;
  require_manufacturer?: string;
  require_model?: string;
  require_android_min?: number | null;
  require_android_max?: number | null;
};
export type ProfileMigration = {
  from_version: string;
  to_version: string;
  profile: Profile;
  warnings: string[];
};
export type ProfilePreview = {
  source_version: string;
  profile: Profile;
  migration: ProfileMigration | null;
  compatible: boolean;
  compatibility_issues: string[];
  android_user: number | null;
  rows: ProfilePreviewRow[];
};
export type ProfilePreviewRow = {
  action: ProfileAction;
  plan: PlannedAction;
  current_state: string;
  expected_state: string;
  status: ProfilePreviewStatus;
  reason: string;
};
export type ProfilePreviewStatus = "ready" | "already_matches" | "missing";
export type ProfileUserMode = "owner" | "current" | "explicit";
export type ProfileUserTarget = { mode?: ProfileUserMode; id?: number | null };
export type Quirk = {
  /**
   * Stable id for cross-referencing in bug reports.
   */
  id: string;
  /**
   * Human-readable title — first line shown to the user.
   */
  title: string;
  /**
   * The matcher. All conditions are AND-ed.
   */
  matches?: QuirkMatch;
  /**
   * Body of the explanation. Markdown allowed; the UI renders
   * inline.
   */
  explanation: string;
  /**
   * Optional suggested next step. The UI may render this as a
   * one-click action button if the kind is recognised.
   */
  mitigation?: Mitigation | null;
};
export type QuirkMatch = {
  /**
   * Substrings to look for in the failing command's stderr or
   * stdout. ANY-match within the field; ALL-match across fields.
   */
  error_contains?: string[];
  /**
   * Manufacturer values that should be present (case-insensitive
   * equality against `ro.product.manufacturer`).
   */
  manufacturer?: string[];
  /**
   * ROM family hints — free-form, case-insensitive substring match
   * against `ro.build.version.incremental` or known fingerprints.
   */
  rom?: string[];
  /**
   * Package id patterns the failed action was applied to (exact
   * match on package id).
   */
  package_id?: string[];
};
export type RecoveryBaseline = {
  format: string;
  schema_version: number;
  exported_at: string;
  device: BaselineDevice;
  android_user: number;
  pack?: BaselinePack | null;
  packages: BaselinePackage[];
};
export type RecoveryBaselineDiff = {
  baseline: RecoveryBaseline;
  compatibility: BaselineCompatibility;
  rows: BaselineDiffRow[];
  plans: PlannedAction[];
};
export type RemoteFileEntry = {
  name: string;
  is_dir: boolean;
  size: number | null;
  permissions: string;
  parse_error?: string | null;
};
export type RemoteFileMutationKind =
  | "mkdir"
  | "rename"
  | "delete_file"
  | "delete_directory";
export type RemoteFileMutationPlan = {
  kind: RemoteFileMutationKind;
  source_path: string;
  destination_path: string | null;
  argv: string[];
  description: string;
  destructive: boolean;
};
export type RemoteFileMutationRequest = {
  kind: RemoteFileMutationKind;
  source_path: string;
  destination_path?: string | null;
};
export type RemoteListing = {
  path: string;
  entries: RemoteFileEntry[];
  free_space_kb: number | null;
};
export type RemovalLevel = "recommended" | "advanced" | "expert" | "unsafe";
export type ResolveSource =
  /**
   * Found on the user's `PATH`.
   */
  | "path"
  /**
   * Found via the `ANDROID_HOME` or `ANDROID_SDK_ROOT` env var.
   */
  | "android_home"
  /**
   * Found at a platform-default Android Studio install location.
   */
  | "android_studio"
  /**
   * Found at a Homebrew prefix on macOS.
   */
  | "homebrew"
  /**
   * Found at a common Linux distro install location.
   */
  | "distro_package"
  /**
   * Bundled with Droidsmith. Reserved for the release pipeline once
   * `bundle.externalBin` and resolver wiring are in place.
   */
  | "bundled"
  /**
   * Not found anywhere we know to look.
   */
  | "not_found";
export type SavedResult = {
  path: string;
  byte_size: number;
  generated_at: string;
};
export type ScrcpyCapabilities = {
  path: string;
  version: string;
  available_video_codecs: string[];
  video_encoders: ScrcpyVideoEncoder[];
  probe_warning: string | null;
  cache_hit: boolean;
  supports_flex_display: boolean;
  supports_keep_active: boolean;
};
export type ScrcpyExitReason =
  | "user_stopped"
  | "unsupported_option"
  | "device_disconnected"
  | "encoder_failed"
  | "permission_denied"
  | "adb_failed"
  | "signaled"
  | "process_exited";
export type ScrcpySession = {
  id: number;
  serial: string;
  pid: number;
  args: string[];
  started_at: string;
  state: ScrcpySessionState;
  exit_code: number | null;
  exit_reason: ScrcpyExitReason | null;
  stderr_tail: string;
};
export type ScrcpySessionState = "running" | "exited" | "stopped";
export type ScrcpyVideoEncoder = {
  codec: string;
  name: string;
  software: boolean;
};
export type SettingsExportResult = {
  path: string;
  byteSize: number;
  scope: SettingsScope;
};
export type SettingsLanguage = "en" | "ru";
export type SettingsLoadResult = {
  settings: SettingsSnapshot;
  recovery: SettingsRecovery;
  legacyCleanupAllowed: boolean;
};
export type SettingsRecovery =
  | "clean"
  | "legacy_imported"
  | "corrupt_quarantined";
export type SettingsScope = "all" | "language" | "mirror_presets";
export type SettingsSnapshot = {
  version: string;
  language: SettingsLanguage | null;
  mirrorPresetCount: number;
};
export type ShellActionPlan = {
  mutating: boolean;
  dangerous: boolean;
  plan: PlannedAction | null;
};
export type StorageInfo = {
  total_kb: number | null;
  used_kb: number | null;
  available_kb: number | null;
};
export type SuggestedInstallOverride =
  | "allow_downgrade"
  | "bypass_low_target_sdk_block";
export type SupportPreview = {
  generated_at: string;
  content: string;
  byte_size: number;
  device_count: number;
  failed_operation_count: number;
  crash_line_count: number;
  local_only: boolean;
};
export type UserScope = "unspecified" | "owner" | "current" | "any";
export type VideoCodec = "h264" | "h265" | "av1" | "vp8" | "vp9";
export type WifiV2State = "supported" | "not_detected" | "probe_unavailable";
export type WipeResult = {
  files_removed: number;
  bytes_removed: number;
  device_journals_preserved: boolean;
};
export type WirelessAdbService = {
  name: string;
  service_type: string;
  kind: WirelessServiceKind;
  host: string;
  port: number;
  endpoint: string;
};
export type WirelessCommandError = {
  code: string;
  message: string;
  hint_code: WirelessFailureHintCode | null;
  diagnostics: WirelessFailureDiagnostics;
};
export type WirelessCommandResult = {
  endpoint: string;
  stdout: string;
  transport_kind: DeviceTransportKind | null;
};
export type WirelessConnectRequest = {
  host: string;
  port: number;
  /**
   * Explicitly labels a manual endpoint as legacy `adb tcpip`. This can
   * never upgrade an endpoint to TLS; exact current mDNS discovery is the
   * only source of `tls_wifi` provenance.
   */
  legacy_tcp?: boolean;
};
export type WirelessEndpointKind = "ip_address" | "local_name";
export type WirelessFailureDiagnostics = {
  platform_tools_version: string | null;
  mdns_enabled: boolean | null;
  mdns_backend: string | null;
  mdns_check_succeeded: boolean;
  active_vpn_interfaces: number;
  endpoint_kind: WirelessEndpointKind;
  adb_error_kind: string;
};
export type WirelessFailureHintCode =
  | "vpn_interference_likely"
  | "mdns_interference_likely";
export type WirelessPairRequest = {
  host: string;
  port: number;
  pairing_code: string;
};
export type WirelessServiceKind = "pairing" | "connect" | "other";

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
